roll-back version of electron-updater, pin it to version known to work
`yarn upgrade` happily updated to a newer version of this dependency, but
newer versions did not play well at runtime, causing the AppImage package
to fail at startup (1). I tried a few versions, starting with newer ones, and
pinned the first one that worked.

(1):

```bash
theia-blueprint$ ./applications/electron/dist/TheiaBlueprint.AppImage
Failed to start the electron application.
Error: Cannot find module 'fs/promises'
Require stack:
- /tmp/.mount_TheiaBXVxquD/resources/app/node_modules/electron-updater/out/AppUpdater.js
- /tmp/.mount_TheiaBXVxquD/resources/app/node_modules/electron-updater/out/main.js
- /tmp/.mount_TheiaBXVxquD/resources/app/node_modules/theia-blueprint-updater/lib/electron-main/update/theia-updater-impl.js
- /tmp/.mount_TheiaBXVxquD/resources/app/node_modules/theia-blueprint-updater/lib/electron-main/update/theia-updater-main-module.js
- /tmp/.mount_TheiaBXVxquD/resources/app/src-gen/frontend/electron-main.js
- /tmp/.mount_TheiaBXVxquD/resources/app/scripts/theia-electron-main.js
-
    at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at Function.o._resolveFilename (electron/js2c/browser_init.js:281:681)
    at Module._load (internal/modules/cjs/loader.js:690:27)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/tmp/.mount_TheiaBXVxquD/resources/app/node_modules/electron-updater/out/AppUpdater.js:8:20)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
    at Module.load (internal/modules/cjs/loader.js:815:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/tmp/.mount_TheiaBXVxquD/resources/app/node_modules/electron-updater/out/AppUpdater.js',
    '/tmp/.mount_TheiaBXVxquD/resources/app/node_modules/electron-updater/out/main.js',
    '/tmp/.mount_TheiaBXVxquD/resources/app/node_modules/theia-blueprint-updater/lib/electron-main/update/theia-updater-impl.js',
    '/tmp/.mount_TheiaBXVxquD/resources/app/node_modules/theia-blueprint-updater/lib/electron-main/update/theia-updater-main-module.js',
    '/tmp/.mount_TheiaBXVxquD/resources/app/src-gen/frontend/electron-main.js',
    '/tmp/.mount_TheiaBXVxquD/resources/app/scripts/theia-electron-main.js',
    undefined
  ]
}
```

Signed-off-by: Marc Dumais <marc.dumais@ericsson.com>